name: "Setup Gradle"
description: "Sets up Java and Gradle"
runs:
  using: "composite"
  steps:
    - name: Set up Generic JDK 25
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "21"

    - name: Grant Execute Permission to Gradle
      shell: bash
      run: chmod +x gradlew
